CHECK_HOSTS = [
    "adf.org.au",
    "adin.com.au",
    "admin.kolmeo.com",
    "admin.liquorice.com.au",
    "atse.liquorice.net.au",
    "atse.org.au",
    "dale.org.au"
    "dokio.co",
    "geelong.liquorice.net.au",
    "geelongartscentre.org.au",
    "goodsports.com.au",
    "intranet.adf.org.au",
    "kolmeo.com",
    "liquorice.com.au",
    "liquorice.com.au",
    "littlepay.com",
    "shop.adf.org.au",
    "thorneharbour.org",
    "vac.org.au",
    "what-works.org",
    # "control-secure.liquorice.com.au",
    # "druginfo.adf.org.au",
]
